# Site settings
exclude: [vendor]
title: 深夜遇見華陰街
email: support@huayinthon.xyz
#baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://sdn.huayinthon.xyz" # the base hostname & protocol for your site
github_username:  huayinthon
permalink: pretty
markdown: rdiscount
highlighter: pygments
encoding: utf-8
timezone: Asia/Taipei
google_analytics: UA-68409135-1
gems:
  - jekyll-redirect-from
